name: Amazon Filter Automation CI

on:
  push:
    branches:
      - feature/google-aggregator-improvements
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        run: mvn -v

      - name: Run Tests with Maven
        run: mvn clean test

      - name: Upload Extent Report
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: test-output/ExtentReports/ExtentReport.html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
