name: CI Pipeline
'on':
  push:
    branches:
      - google-aggregator-pom-updated
  workflow_dispatch: null
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24
      - name: Run Maven Tests
        working-directory: Intro
        run: mvn clean test
