name: CI Pipeline - Publish Extent (gh-pages)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
  schedule:
    - cron: "50 17 * * *"

permissions:
  contents: write

env:
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 24
  WORKDIR: eclipse-workspace/Intro
  ARTIFACT_RETENTION_DAYS: 7

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 300

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Set RUN_TIMESTAMP (Windows runner)
        id: set_ts
        shell: pwsh
        run: |
          $ts = Get-Date -Format 'yyyy-MM-dd_HH-mm-ss'
          Write-Host "RUN_TIMESTAMP = $ts"
          Add-Content -Path $env:GITHUB_ENV -Value "RUN_TIMESTAMP=$ts"

      - name: Run Maven Tests (enforce logs.dir + runTimestamp)
        working-directory: ${{ env.WORKDIR }}
        shell: bash
        run: |
          ABS_LOGS_DIR="${GITHUB_WORKSPACE}/${{ env.WORKDIR }}/logs/run_${{ env.RUN_TIMESTAMP }}"
          echo "Setting logs.dir = $ABS_LOGS_DIR"
          mvn -B -ntp clean test -DrunTimestamp="${{ env.RUN_TIMESTAMP }}" -Dlogs.dir="$ABS_LOGS_DIR" | tee mvn-output.txt
          tail -n 200 mvn-output.txt || true

      - name: Package Extent Report bundle with screenshots and logs
        if: always()
        shell: bash
        working-directory: ${{ env.WORKDIR }}
        run: |
          set -euo pipefail
          rm -rf artifacts/extent
          mkdir -p artifacts/extent

          if [ -d "test-output/ExtentReports" ]; then
            cp -r test-output/ExtentReports artifacts/extent/ExtentReports
          fi

          if [ -d "test-output/screenshots" ]; then
            cp -r test-output/screenshots artifacts/extent/screenshots
          fi

          mkdir -p artifacts/extent/logs
          if [ -d "logs/run_${RUN_TIMESTAMP}" ]; then
            cp -r "logs/run_${RUN_TIMESTAMP}" artifacts/extent/logs/
          else
            cp -r logs/run_* artifacts/extent/logs/ || true
          fi

          cat > artifacts/extent/index.html <<'HTML'
          <!doctype html>
          <html>
          <head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=ExtentReports/ExtentReport.html"><title>Latest Test Report</title></head>
          <body>If you are not redirected, <a href="ExtentReports/ExtentReport.html">open the report</a>.</body>
          </html>
          HTML

      - name: Upload Extent Report Bundle (HTML + screenshots + logs)  # optional, keeps copy on run
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report-bundle
          path: ${{ env.WORKDIR }}/artifacts/extent
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: warn

      # <-- DEPLOY STEP: skip when running on gh-pages itself to avoid "deploy from gh-pages to gh-pages" error -->
      - name: Deploy Extent Report to GitHub Pages (gh-pages)
        if: ${{ always() && github.ref_name != 'gh-pages' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/${{ env.WORKDIR }}/artifacts/extent
          publish_branch: gh-pages
          keep_files: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "ci: publish extent report and assets (${{ env.RUN_TIMESTAMP }}) [skip ci]"

      - name: Upload Raw Logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: framework-logs
          path: |
            ${{ env.WORKDIR }}/logs
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: ignore
